//! Behaviour tags for abilities, items and scripted moves.
//!
//! Showdown implements these with event callbacks; the engine implements each
//! one explicitly at fixed hook points. An id that is not listed here maps to
//! `Other` / `MoveFx::None`, and the dex loader marks it unsupported if
//! Showdown gives it any scripted behaviour. Adding a variant here is a
//! promise that the battle code implements it.

macro_rules! tag_enum {
    ($name:ident { $($variant:ident = $id:literal),* $(,)? }) => {
        #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, Default)]
        pub enum $name {
            #[default]
            Other,
            $($variant),*
        }
        impl $name {
            pub fn from_id(id: &str) -> $name {
                match id {
                    $($id => $name::$variant,)*
                    _ => $name::Other,
                }
            }
            pub const IMPLEMENTED: &'static [&'static str] = &[$($id),*];
        }
    };
}

tag_enum!(Ab {
    Adaptability = "adaptability",
    Aerilate = "aerilate",
    AirLock = "airlock",
    Analytic = "analytic",
    ArmorTail = "armortail",
    AuraGuard = "auraguard",
    BattleArmor = "battlearmor",
    Berserk = "berserk",
    BigPecks = "bigpecks",
    Blaze = "blaze",
    Chlorophyll = "chlorophyll",
    ClearBody = "clearbody",
    CloudNine = "cloudnine",
    Competitive = "competitive",
    CompoundEyes = "compoundeyes",
    Contrary = "contrary",
    Corrosion = "corrosion",
    CuriousMedicine = "curiousmedicine",
    CursedBody = "cursedbody",
    CuteCharm = "cutecharm",
    Damp = "damp",
    Dazzling = "dazzling",
    Defiant = "defiant",
    Dragonize = "dragonize",
    Drizzle = "drizzle",
    Drought = "drought",
    DrySkin = "dryskin",
    EarthEater = "eartheater",
    Eelevate = "eelevate",
    ElectricSurge = "electricsurge",
    Electromorphosis = "electromorphosis",
    EmergencyExit = "emergencyexit",
    FairyAura = "fairyaura",
    Filter = "filter",
    FireMane = "firemane",
    FlameBody = "flamebody",
    FlashFire = "flashfire",
    FlowerVeil = "flowerveil",
    Fluffy = "fluffy",
    FriendGuard = "friendguard",
    Frisk = "frisk",
    FullMetalBody = "fullmetalbody",
    GaleWings = "galewings",
    Galvanize = "galvanize",
    GoodAsGold = "goodasgold",
    GrassySurge = "grassysurge",
    Guts = "guts",
    Healer = "healer",
    Hospitality = "hospitality",
    HugePower = "hugepower",
    Hustle = "hustle",
    HyperCutter = "hypercutter",
    IceBody = "icebody",
    Illuminate = "illuminate",
    Infiltrator = "infiltrator",
    InnardsOut = "innardsout",
    InnerFocus = "innerfocus",
    Insomnia = "insomnia",
    Intimidate = "intimidate",
    IronBarbs = "ironbarbs",
    IronFist = "ironfist",
    Justified = "justified",
    LeafGuard = "leafguard",
    Levitate = "levitate",
    Libero = "libero",
    LightningRod = "lightningrod",
    Limber = "limber",
    LiquidVoice = "liquidvoice",
    MagicBounce = "magicbounce",
    MagicGuard = "magicguard",
    Magician = "magician",
    MagmaArmor = "magmaarmor",
    MarvelScale = "marvelscale",
    MegaLauncher = "megalauncher",
    MegaSol = "megasol",
    MirrorArmor = "mirrorarmor",
    MistySurge = "mistysurge",
    MoldBreaker = "moldbreaker",
    Moody = "moody",
    MotorDrive = "motordrive",
    Moxie = "moxie",
    Multiscale = "multiscale",
    NaturalCure = "naturalcure",
    NoGuard = "noguard",
    Oblivious = "oblivious",
    Overcoat = "overcoat",
    Overgrow = "overgrow",
    OwnTempo = "owntempo",
    ParentalBond = "parentalbond",
    Pickpocket = "pickpocket",
    PiercingDrill = "piercingdrill",
    Pixilate = "pixilate",
    PoisonPoint = "poisonpoint",
    PoisonTouch = "poisontouch",
    Prankster = "prankster",
    Pressure = "pressure",
    Protean = "protean",
    PsychicSurge = "psychicsurge",
    PunkRock = "punkrock",
    PurePower = "purepower",
    QueenlyMajesty = "queenlymajesty",
    QuickFeet = "quickfeet",
    RainDish = "raindish",
    Rattled = "rattled",
    Refrigerate = "refrigerate",
    Regenerator = "regenerator",
    Rivalry = "rivalry",
    RockHead = "rockhead",
    RoughSkin = "roughskin",
    RunAway = "runaway",
    SandForce = "sandforce",
    SandRush = "sandrush",
    SandStream = "sandstream",
    SandVeil = "sandveil",
    Sapsipper = "sapsipper",
    Scrappy = "scrappy",
    ShadowTag = "shadowtag",
    Sharpness = "sharpness",
    SheerForce = "sheerforce",
    ShellArmor = "shellarmor",
    ShieldDust = "shielddust",
    SlushRush = "slushrush",
    Sniper = "sniper",
    SnowCloak = "snowcloak",
    SnowWarning = "snowwarning",
    SolarPower = "solarpower",
    SolidRock = "solidrock",
    Soundproof = "soundproof",
    SpeedBoost = "speedboost",
    SpicySpray = "spicyspray",
    Stalwart = "stalwart",
    Stamina = "stamina",
    Static = "static",
    Steadfast = "steadfast",
    StormDrain = "stormdrain",
    StrongJaw = "strongjaw",
    Sturdy = "sturdy",
    SuperLuck = "superluck",
    SupremeOverlord = "supremeoverlord",
    SurgeSurfer = "surgesurfer",
    Swarm = "swarm",
    SweetVeil = "sweetveil",
    SwiftSwim = "swiftswim",
    Symbiosis = "symbiosis",
    Synchronize = "synchronize",
    Technician = "technician",
    Telepathy = "telepathy",
    ThermalExchange = "thermalexchange",
    ThickFat = "thickfat",
    TintedLens = "tintedlens",
    Torrent = "torrent",
    ToughClaws = "toughclaws",
    ToxicDebris = "toxicdebris",
    Trace = "trace",
    Unaware = "unaware",
    Unburden = "unburden",
    Unnerve = "unnerve",
    UnseenFist = "unseenfist",
    VitalSpirit = "vitalspirit",
    VoltAbsorb = "voltabsorb",
    WaterAbsorb = "waterabsorb",
    WaterBubble = "waterbubble",
    WeakArmor = "weakarmor",
    WellBakedBody = "wellbakedbody",
    WhiteSmoke = "whitesmoke",
    WimpOut = "wimpout",
    WindRider = "windrider",
});

tag_enum!(It {
    AirBalloon = "airballoon",
    BigRoot = "bigroot",
    BlackBelt = "blackbelt",
    BlackGlasses = "blackglasses",
    BrightPowder = "brightpowder",
    Charcoal = "charcoal",
    ChoiceBand = "choiceband",
    ChoiceScarf = "choicescarf",
    ChoiceSpecs = "choicespecs",
    DampRock = "damprock",
    DragonFang = "dragonfang",
    EjectButton = "ejectbutton",
    ElectricSeed = "electricseed",
    ExpertBelt = "expertbelt",
    FairyFeather = "fairyfeather",
    FocusSash = "focussash",
    GrassySeed = "grassyseed",
    HardStone = "hardstone",
    HeatRock = "heatrock",
    IcyRock = "icyrock",
    IronBall = "ironball",
    KingsRock = "kingsrock",
    Leftovers = "leftovers",
    LifeOrb = "lifeorb",
    LightClay = "lightclay",
    Magnet = "magnet",
    MentalHerb = "mentalherb",
    MetalCoat = "metalcoat",
    MiracleSeed = "miracleseed",
    MistySeed = "mistyseed",
    MuscleBand = "muscleband",
    MysticWater = "mysticwater",
    NeverMeltIce = "nevermeltice",
    PoisonBarb = "poisonbarb",
    PsychicSeed = "psychicseed",
    QuickClaw = "quickclaw",
    RazorClaw = "razorclaw",
    RedCard = "redcard",
    RockyHelmet = "rockyhelmet",
    ScopeLens = "scopelens",
    SharpBeak = "sharpbeak",
    ShellBell = "shellbell",
    SilkScarf = "silkscarf",
    SilverPowder = "silverpowder",
    SmoothRock = "smoothrock",
    SoftSand = "softsand",
    SpellTag = "spelltag",
    TerrainExtender = "terrainextender",
    TwistedSpoon = "twistedspoon",
    WhiteHerb = "whiteherb",
    WideLens = "widelens",
    WiseGlasses = "wiseglasses",
    ZoomLens = "zoomlens",
    // Berries
    SitrusBerry = "sitrusberry",
    LumBerry = "lumberry",
    ChestoBerry = "chestoberry",
    CheriBerry = "cheriberry",
    PechaBerry = "pechaberry",
    RawstBerry = "rawstberry",
    AspearBerry = "aspearberry",
    PersimBerry = "persimberry",
    OranBerry = "oranberry",
    // Type-resist berries
    BabiriBerry = "babiriberry",
    ChartiBerry = "chartiberry",
    ChilanBerry = "chilanberry",
    ChopleBerry = "chopleberry",
    CobaBerry = "cobaberry",
    ColburBerry = "colburberry",
    HabanBerry = "habanberry",
    KasibBerry = "kasibberry",
    KebiaBerry = "kebiaberry",
    OccaBerry = "occaberry",
    PasshoBerry = "passhoberry",
    PayapaBerry = "payapaberry",
    RindoBerry = "rindoberry",
    RoseliBerry = "roseliberry",
    ShucaBerry = "shucaberry",
    TangaBerry = "tangaberry",
    WacanBerry = "wacanberry",
    YacheBerry = "yacheberry",
});

tag_enum!(MoveFx {
    Protect = "protect",
    Detect = "detect",
    SpikyShield = "spikyshield",
    BanefulBunker = "banefulbunker",
    KingsShield = "kingsshield",
    SilkTrap = "silktrap",
    BurningBulwark = "burningbulwark",
    Endure = "endure",
    WideGuard = "wideguard",
    QuickGuard = "quickguard",
    FakeOut = "fakeout",
    FirstImpression = "firstimpression",
    GrassyGlide = "grassyglide",
    SuckerPunch = "suckerpunch",
    UpperHand = "upperhand",
    PartingShot = "partingshot",
    HelpingHand = "helpinghand",
    FollowMe = "followme",
    RagePowder = "ragepowder",
    ExpandingForce = "expandingforce",
    WeatherBall = "weatherball",
    TerrainPulse = "terrainpulse",
    LastRespects = "lastrespects",
    LowKick = "lowkick",
    GrassKnot = "grassknot",
    HeavySlam = "heavyslam",
    HeatCrash = "heatcrash",
    Eruption = "eruption",
    WaterSpout = "waterspout",
    DragonEnergy = "dragonenergy",
    Acrobatics = "acrobatics",
    StompingTantrum = "stompingtantrum",
    TemperFlare = "temperflare",
    RageFist = "ragefist",
    Hex = "hex",
    Venoshock = "venoshock",
    BarbBarrage = "barbbarrage",
    Facade = "facade",
    KnockOff = "knockoff",
    LashOut = "lashout",
    Payback = "payback",
    StoredPower = "storedpower",
    PowerTrip = "powertrip",
    ElectroBall = "electroball",
    HardPress = "hardpress",
    RisingVoltage = "risingvoltage",
    TripleAxel = "tripleaxel",
    DireClaw = "direclaw",
    TriAttack = "triattack",
    ThroatChop = "throatchop",
    BurningJealousy = "burningjealousy",
    AlluringVoice = "alluringvoice",
    Hurricane = "hurricane",
    Thunder = "thunder",
    Blizzard = "blizzard",
    ElectroShot = "electroshot",
    SolarBeam = "solarbeam",
    SolarBlade = "solarblade",
    MeteorBeam = "meteorbeam",
    PhantomForce = "phantomforce",
    ShadowForce = "shadowforce",
    Fly = "fly",
    Bounce = "bounce",
    Dig = "dig",
    Dive = "dive",
    GlaiveRush = "glaiverush",
    Encore = "encore",
    Taunt = "taunt",
    Disable = "disable",
    Imprison = "imprison",
    Yawn = "yawn",
    PerishSong = "perishsong",
    LeechSeed = "leechseed",
    Substitute = "substitute",
    Trick = "trick",
    Switcheroo = "switcheroo",
    Roost = "roost",
    AuroraVeil = "auroraveil",
    PsychicFangs = "psychicfangs",
    BrickBreak = "brickbreak",
    RagingBull = "ragingbull",
    FreezeDry = "freezedry",
    DoubleShock = "doubleshock",
    BurnUp = "burnup",
    SuperFang = "superfang",
    FinalGambit = "finalgambit",
    Endeavor = "endeavor",
    Haze = "haze",
    ClearSmog = "clearsmog",
    StrengthSap = "strengthsap",
    HealPulse = "healpulse",
    FloralHealing = "floralhealing",
    PollenPuff = "pollenpuff",
    PainSplit = "painsplit",
    BellyDrum = "bellydrum",
    AfterYou = "afteryou",
    Quash = "quash",
    Soak = "soak",
    SkillSwap = "skillswap",
    Entrainment = "entrainment",
    WorrySeed = "worryseed",
    Poltergeist = "poltergeist",
    BugBite = "bugbite",
    SteelBeam = "steelbeam",
    HighJumpKick = "highjumpkick",
    StoneAxe = "stoneaxe",
    CeaselessEdge = "ceaselessedge",
    MortalSpin = "mortalspin",
    IceSpinner = "icespinner",
    SteelRoller = "steelroller",
    Curse = "curse",
    Growth = "growth",
    Acupressure = "acupressure",
    ClangorousSoul = "clangoroussoul",
    Rest = "rest",
    Wish = "wish",
    HealingWish = "healingwish",
    BatonPass = "batonpass",
    ShedTail = "shedtail",
    Round = "round",
    BeatUp = "beatup",
    WaterShuriken = "watershuriken",
    Assurance = "assurance",
    PsychUp = "psychup",
    TopsyTurvy = "topsyturvy",
    FocusEnergy = "focusenergy",
    DragonCheer = "dragoncheer",
    Feint = "feint",
    StealthRock = "stealthrock",
    ToxicSpikes = "toxicspikes",
    Defog = "defog",
    NoRetreat = "noretreat",
    Recycle = "recycle",
    Moonlight = "moonlight",
    MorningSun = "morningsun",
    Synthesis = "synthesis",
    ShoreUp = "shoreup",
    DestinyBond = "destinybond",
    TidyUp = "tidyup",
    LastResort = "lastresort",
    Counter = "counter",
    MirrorCoat = "mirrorcoat",
    MetalBurst = "metalburst",
});

/// Moves whose Showdown callbacks are fully reproduced by the engine's generic
/// handling of their data (side conditions, field effects, volatiles).
pub fn move_callbacks_are_generic(id: &str) -> bool {
    matches!(
        id,
        "tailwind"
            | "trickroom"
            | "gravity"
            | "reflect"
            | "lightscreen"
            | "safeguard"
            | "mist"
            | "raindance"
            | "sunnyday"
            | "sandstorm"
            | "snowscape"
            | "grassyterrain"
            | "psychicterrain"
            | "electricterrain"
            | "mistyterrain"
            | "confuseray"
            | "magnetrise"
            | "aquaring"
            | "ingrain"
            | "saltcure"
            | "laserfocus"
            | "charge"
            | "tarshot"
            | "smackdown"
            | "torment"
            | "healblock"
            | "attract"
    )
}
